models:
  - name: prodraw_orders__stag_orders
    description: Order data with basic cleaning and transformation applied, one row per order.
    config:
      alias: orders
      columns:
        - name: order_id
          description: The unique key for each order.
          data_tests:
            - not_null
            - unique
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "order_total - tax_paid = subtotal"  