
models:
  - name: prodraw_stores__stag_locations
    description: Store location data with basic cleaning and transformation applied
    config:
      alias: locations
      columns:
        - name: location_id
          description: The unique key for each location of the store
          data_tests:
            - not_null
            - unique
unit_tests:
  - name: test_does_location_opened_at_trunc_to_date
    description: "Check that open_at timestamp is properly truncated to a date."
    model: prodraw_stores__stag_locations
    given:
      - input: source('sales', 'stores')
        # the bracket for rows should be curly brackets
        rows:
          - {
              id: 1,
              name: "Vice City",
              tax_rate: 0.2,
              opened_at: "2016-09-01T00:00:00",
            }
          - {
              id: 2,
              name: "San Andreas",
              tax_rate: 0.1,
              opened_at: "2019-10-27T23:59:59.9999",
            }
    expect:
      rows:
        - {
            location_id: 1,
            location_name: "Vice City",
            tax_rate: 0.2,
            opened_date: "2016-09-01"
          }
        - {
            location_id: 2,
            location_name: "San Andreas",
            tax_rate: 0.1,
            opened_date: "2019-10-27"
          }
